# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Callable,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = Literal['default', 'insensitive']
SortOrder = Literal['asc', 'desc']


class _DatasourceOverrideOptional(TypedDict, total=False):
    env: str
    name: str


class DatasourceOverride(_DatasourceOverrideOptional):
    url: str


# NOTE: we don't support some options as their type hints are not publicly exposed
# https://github.com/encode/httpx/discussions/1977
class HttpConfig(TypedDict, total=False):
    app: Callable[[Mapping[str, Any], Any], Any]
    http1: bool
    http2: bool
    limits: httpx.Limits
    timeout: Union[None, float, httpx.Timeout]
    trust_env: bool
    max_redirects: int


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[str]]


class _StringListFilterHasInput(TypedDict):
    has: str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[str]


class _StringListUpdatePush(TypedDict):
    push: List[str]


StringListUpdate = Union[
    List[str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[bool]


BooleanListUpdate = Union[
    List[bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[int]]


class _IntListFilterHasInput(TypedDict):
    has: int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[int]


class _IntListUpdatePush(TypedDict):
    push: List[int]


IntListUpdate = Union[
    List[int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[int]]


class _BigIntListFilterHasInput(TypedDict):
    has: int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[int]


class _BigIntListUpdatePush(TypedDict):
    push: List[int]


BigIntListUpdate = Union[
    List[int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[float]]


class _FloatListFilterHasInput(TypedDict):
    has: float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[float]


class _FloatListUpdatePush(TypedDict):
    push: List[float]


FloatListUpdate = Union[
    List[float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# Users types

class UsersOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Users create method"""
    id: int
    keywords: List[str]


class UsersCreateInput(UsersOptionalCreateInput):
    """Required arguments to the Users create method"""
    name: str
    role: str
    email: str
    phone: str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class UsersOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Users create method, without relations"""
    id: int
    keywords: List[str]


class UsersCreateWithoutRelationsInput(UsersOptionalCreateWithoutRelationsInput):
    """Required arguments to the Users create method, without relations"""
    name: str
    role: str
    email: str
    phone: str


class UsersCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'UsersCreateWithoutRelationsInput'
    connect: 'UsersWhereUniqueInput'


class UsersCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['UsersCreateWithoutRelationsInput', List['UsersCreateWithoutRelationsInput']]
    connect: Union['UsersWhereUniqueInput', List['UsersWhereUniqueInput']]


_UsersWhereUnique_id_Input = TypedDict(
    '_UsersWhereUnique_id_Input',
    {
        'id': 'int',
    },
    total=True
)

UsersWhereUniqueInput = _UsersWhereUnique_id_Input


class UsersUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, int]
    name: str
    role: str
    email: str
    phone: str
    keywords: 'types.StringListUpdate'


class UsersUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, int]
    name: str
    role: str
    email: str
    phone: str
    keywords: 'types.StringListUpdate'


class UsersUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['UsersCreateWithoutRelationsInput']
    connect: List['UsersWhereUniqueInput']
    set: List['UsersWhereUniqueInput']
    disconnect: List['UsersWhereUniqueInput']
    delete: List['UsersWhereUniqueInput']

    # TODO
    # update: List['UsersUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['UsersUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['UsersScalarWhereInput']
    # upsert: List['UsersUpserteWithWhereUniqueWithoutRelationsInput']
    # connectOrCreate: List['UsersCreateOrConnectWithoutRelationsInput']


class UsersUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'UsersCreateWithoutRelationsInput'
    connect: 'UsersWhereUniqueInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'UsersUpdateInput'
    # upsert: 'UsersUpsertWithoutRelationsInput'
    # connectOrCreate: 'UsersCreateOrConnectWithoutRelationsInput'


class UsersUpsertInput(TypedDict):
    create: 'UsersCreateInput'
    update: 'UsersUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Users_id_OrderByInput = TypedDict(
    '_Users_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Users_name_OrderByInput = TypedDict(
    '_Users_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_Users_role_OrderByInput = TypedDict(
    '_Users_role_OrderByInput',
    {
        'role': 'SortOrder',
    },
    total=True
)

_Users_email_OrderByInput = TypedDict(
    '_Users_email_OrderByInput',
    {
        'email': 'SortOrder',
    },
    total=True
)

_Users_phone_OrderByInput = TypedDict(
    '_Users_phone_OrderByInput',
    {
        'phone': 'SortOrder',
    },
    total=True
)

_Users_keywords_OrderByInput = TypedDict(
    '_Users_keywords_OrderByInput',
    {
        'keywords': 'SortOrder',
    },
    total=True
)

UsersOrderByInput = Union[
    '_Users_id_OrderByInput',
    '_Users_name_OrderByInput',
    '_Users_role_OrderByInput',
    '_Users_email_OrderByInput',
    '_Users_phone_OrderByInput',
    '_Users_keywords_OrderByInput',
]



# recursive Users types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

UsersRelationFilter = TypedDict(
    'UsersRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class UsersListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class UsersInclude(TypedDict, total=False):
    """Users relational arguments"""


    

class UsersIncludeFromUsers(TypedDict, total=False):
    """Relational arguments for Users"""


class UsersIncludeFromUsersRecursive1(TypedDict, total=False):
    """Relational arguments for Users"""


class UsersIncludeFromUsersRecursive2(TypedDict, total=False):
    """Relational arguments for Users"""


class UsersIncludeFromUsersRecursive3(TypedDict, total=False):
    """Relational arguments for Users"""


class UsersIncludeFromUsersRecursive4(TypedDict, total=False):
    """Relational arguments for Users"""

    

class UsersArgsFromUsers(TypedDict, total=False):
    """Arguments for Users"""
    include: 'UsersIncludeFromUsersRecursive1'


class UsersArgsFromUsersRecursive1(TypedDict, total=False):
    """Arguments for Users"""
    include: 'UsersIncludeFromUsersRecursive2'


class UsersArgsFromUsersRecursive2(TypedDict, total=False):
    """Arguments for Users"""
    include: 'UsersIncludeFromUsersRecursive3'


class UsersArgsFromUsersRecursive3(TypedDict, total=False):
    """Arguments for Users"""
    include: 'UsersIncludeFromUsersRecursive4'


class UsersArgsFromUsersRecursive4(TypedDict, total=False):
    """Arguments for Users"""
    
    

class FindManyUsersArgsFromUsers(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive1'


class FindManyUsersArgsFromUsersRecursive1(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive2'


class FindManyUsersArgsFromUsersRecursive2(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive3'


class FindManyUsersArgsFromUsersRecursive3(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive4'


class FindManyUsersArgsFromUsersRecursive4(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    
    

class SearchsIncludeFromUsers(TypedDict, total=False):
    """Relational arguments for Users"""


class SearchsIncludeFromUsersRecursive1(TypedDict, total=False):
    """Relational arguments for Users"""


class SearchsIncludeFromUsersRecursive2(TypedDict, total=False):
    """Relational arguments for Users"""


class SearchsIncludeFromUsersRecursive3(TypedDict, total=False):
    """Relational arguments for Users"""


class SearchsIncludeFromUsersRecursive4(TypedDict, total=False):
    """Relational arguments for Users"""

    

class SearchsArgsFromUsers(TypedDict, total=False):
    """Arguments for Users"""
    include: 'SearchsIncludeFromSearchsRecursive1'


class SearchsArgsFromUsersRecursive1(TypedDict, total=False):
    """Arguments for Users"""
    include: 'SearchsIncludeFromSearchsRecursive2'


class SearchsArgsFromUsersRecursive2(TypedDict, total=False):
    """Arguments for Users"""
    include: 'SearchsIncludeFromSearchsRecursive3'


class SearchsArgsFromUsersRecursive3(TypedDict, total=False):
    """Arguments for Users"""
    include: 'SearchsIncludeFromSearchsRecursive4'


class SearchsArgsFromUsersRecursive4(TypedDict, total=False):
    """Arguments for Users"""
    
    

class FindManySearchsArgsFromUsers(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive1'


class FindManySearchsArgsFromUsersRecursive1(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive2'


class FindManySearchsArgsFromUsersRecursive2(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive3'


class FindManySearchsArgsFromUsersRecursive3(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive4'


class FindManySearchsArgsFromUsersRecursive4(TypedDict, total=False):
    """Arguments for Users"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    


FindManyUsersArgs = FindManyUsersArgsFromUsers
FindFirstUsersArgs = FindManyUsersArgsFromUsers


    

class UsersWhereInput(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntFilter']
    name: Union[str, 'types.StringFilter']
    role: Union[str, 'types.StringFilter']
    email: Union[str, 'types.StringFilter']
    phone: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['UsersWhereInputRecursive1', List['UsersWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['UsersWhereInputRecursive1']
    OR: List['UsersWhereInputRecursive1']
    NOT: List['UsersWhereInputRecursive1']


class UsersWhereInputRecursive1(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntFilter']
    name: Union[str, 'types.StringFilter']
    role: Union[str, 'types.StringFilter']
    email: Union[str, 'types.StringFilter']
    phone: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['UsersWhereInputRecursive2', List['UsersWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['UsersWhereInputRecursive2']
    OR: List['UsersWhereInputRecursive2']
    NOT: List['UsersWhereInputRecursive2']


class UsersWhereInputRecursive2(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntFilter']
    name: Union[str, 'types.StringFilter']
    role: Union[str, 'types.StringFilter']
    email: Union[str, 'types.StringFilter']
    phone: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['UsersWhereInputRecursive3', List['UsersWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['UsersWhereInputRecursive3']
    OR: List['UsersWhereInputRecursive3']
    NOT: List['UsersWhereInputRecursive3']


class UsersWhereInputRecursive3(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntFilter']
    name: Union[str, 'types.StringFilter']
    role: Union[str, 'types.StringFilter']
    email: Union[str, 'types.StringFilter']
    phone: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['UsersWhereInputRecursive4', List['UsersWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['UsersWhereInputRecursive4']
    OR: List['UsersWhereInputRecursive4']
    NOT: List['UsersWhereInputRecursive4']


class UsersWhereInputRecursive4(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntFilter']
    name: Union[str, 'types.StringFilter']
    role: Union[str, 'types.StringFilter']
    email: Union[str, 'types.StringFilter']
    phone: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'



# aggregate Users types


    

class UsersScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    name: Union[str, 'types.StringWithAggregatesFilter']
    role: Union[str, 'types.StringWithAggregatesFilter']
    email: Union[str, 'types.StringWithAggregatesFilter']
    phone: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['UsersScalarWhereWithAggregatesInputRecursive1']
    OR: List['UsersScalarWhereWithAggregatesInputRecursive1']
    NOT: List['UsersScalarWhereWithAggregatesInputRecursive1']


class UsersScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    name: Union[str, 'types.StringWithAggregatesFilter']
    role: Union[str, 'types.StringWithAggregatesFilter']
    email: Union[str, 'types.StringWithAggregatesFilter']
    phone: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['UsersScalarWhereWithAggregatesInputRecursive2']
    OR: List['UsersScalarWhereWithAggregatesInputRecursive2']
    NOT: List['UsersScalarWhereWithAggregatesInputRecursive2']


class UsersScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    name: Union[str, 'types.StringWithAggregatesFilter']
    role: Union[str, 'types.StringWithAggregatesFilter']
    email: Union[str, 'types.StringWithAggregatesFilter']
    phone: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['UsersScalarWhereWithAggregatesInputRecursive3']
    OR: List['UsersScalarWhereWithAggregatesInputRecursive3']
    NOT: List['UsersScalarWhereWithAggregatesInputRecursive3']


class UsersScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    name: Union[str, 'types.StringWithAggregatesFilter']
    role: Union[str, 'types.StringWithAggregatesFilter']
    email: Union[str, 'types.StringWithAggregatesFilter']
    phone: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['UsersScalarWhereWithAggregatesInputRecursive4']
    OR: List['UsersScalarWhereWithAggregatesInputRecursive4']
    NOT: List['UsersScalarWhereWithAggregatesInputRecursive4']


class UsersScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Users arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    name: Union[str, 'types.StringWithAggregatesFilter']
    role: Union[str, 'types.StringWithAggregatesFilter']
    email: Union[str, 'types.StringWithAggregatesFilter']
    phone: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']



class UsersGroupByOutput(TypedDict, total=False):
    id: int
    name: str
    role: str
    email: str
    phone: str
    keywords: List[str]
    _sum: 'UsersSumAggregateOutput'
    _avg: 'UsersAvgAggregateOutput'
    _min: 'UsersMinAggregateOutput'
    _max: 'UsersMaxAggregateOutput'
    _count: 'UsersCountAggregateOutput'


class UsersAvgAggregateOutput(TypedDict, total=False):
    """Users output for aggregating averages"""
    id: float


class UsersSumAggregateOutput(TypedDict, total=False):
    """Users output for aggregating sums"""
    id: int


class UsersScalarAggregateOutput(TypedDict, total=False):
    """Users output including scalar fields"""
    id: int
    name: str
    role: str
    email: str
    phone: str
    keywords: List[str]


UsersMinAggregateOutput = UsersScalarAggregateOutput
UsersMaxAggregateOutput = UsersScalarAggregateOutput


class UsersMaxAggregateInput(TypedDict, total=False):
    """Users input for aggregating by max"""
    id: bool
    name: bool
    role: bool
    email: bool
    phone: bool
    keywords: bool


class UsersMinAggregateInput(TypedDict, total=False):
    """Users input for aggregating by min"""
    id: bool
    name: bool
    role: bool
    email: bool
    phone: bool
    keywords: bool


class UsersNumberAggregateInput(TypedDict, total=False):
    """Users input for aggregating numbers"""
    id: bool


UsersAvgAggregateInput = UsersNumberAggregateInput
UsersSumAggregateInput = UsersNumberAggregateInput


UsersCountAggregateInput = TypedDict(
    'UsersCountAggregateInput',
    {
        'id': bool,
        'name': bool,
        'role': bool,
        'email': bool,
        'phone': bool,
        'keywords': bool,
        '_all': bool,
    },
    total=False,
)

UsersCountAggregateOutput = TypedDict(
    'UsersCountAggregateOutput',
    {
        'id': int,
        'name': int,
        'role': int,
        'email': int,
        'phone': int,
        'keywords': int,
        '_all': int,
    },
    total=False,
)


UsersKeys = Literal[
    'id',
    'name',
    'role',
    'email',
    'phone',
    'keywords',
]
UsersScalarFieldKeys = Literal[
    'id',
    'name',
    'role',
    'email',
    'phone',
    'keywords',
]
UsersScalarFieldKeysT = TypeVar('UsersScalarFieldKeysT', bound=UsersScalarFieldKeys)

UsersRelationalFieldKeys = _NoneType

# Searchs types

class SearchsOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Searchs create method"""
    id: int
    keywords: List[str]


class SearchsCreateInput(SearchsOptionalCreateInput):
    """Required arguments to the Searchs create method"""
    title: str
    snippet: str
    link: str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class SearchsOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Searchs create method, without relations"""
    id: int
    keywords: List[str]


class SearchsCreateWithoutRelationsInput(SearchsOptionalCreateWithoutRelationsInput):
    """Required arguments to the Searchs create method, without relations"""
    title: str
    snippet: str
    link: str


class SearchsCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'SearchsCreateWithoutRelationsInput'
    connect: 'SearchsWhereUniqueInput'


class SearchsCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['SearchsCreateWithoutRelationsInput', List['SearchsCreateWithoutRelationsInput']]
    connect: Union['SearchsWhereUniqueInput', List['SearchsWhereUniqueInput']]


_SearchsWhereUnique_id_Input = TypedDict(
    '_SearchsWhereUnique_id_Input',
    {
        'id': 'int',
    },
    total=True
)

SearchsWhereUniqueInput = _SearchsWhereUnique_id_Input


class SearchsUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, int]
    title: str
    snippet: str
    link: str
    keywords: 'types.StringListUpdate'


class SearchsUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, int]
    title: str
    snippet: str
    link: str
    keywords: 'types.StringListUpdate'


class SearchsUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['SearchsCreateWithoutRelationsInput']
    connect: List['SearchsWhereUniqueInput']
    set: List['SearchsWhereUniqueInput']
    disconnect: List['SearchsWhereUniqueInput']
    delete: List['SearchsWhereUniqueInput']

    # TODO
    # update: List['SearchsUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['SearchsUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['SearchsScalarWhereInput']
    # upsert: List['SearchsUpserteWithWhereUniqueWithoutRelationsInput']
    # connectOrCreate: List['SearchsCreateOrConnectWithoutRelationsInput']


class SearchsUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'SearchsCreateWithoutRelationsInput'
    connect: 'SearchsWhereUniqueInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'SearchsUpdateInput'
    # upsert: 'SearchsUpsertWithoutRelationsInput'
    # connectOrCreate: 'SearchsCreateOrConnectWithoutRelationsInput'


class SearchsUpsertInput(TypedDict):
    create: 'SearchsCreateInput'
    update: 'SearchsUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Searchs_id_OrderByInput = TypedDict(
    '_Searchs_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Searchs_title_OrderByInput = TypedDict(
    '_Searchs_title_OrderByInput',
    {
        'title': 'SortOrder',
    },
    total=True
)

_Searchs_snippet_OrderByInput = TypedDict(
    '_Searchs_snippet_OrderByInput',
    {
        'snippet': 'SortOrder',
    },
    total=True
)

_Searchs_link_OrderByInput = TypedDict(
    '_Searchs_link_OrderByInput',
    {
        'link': 'SortOrder',
    },
    total=True
)

_Searchs_keywords_OrderByInput = TypedDict(
    '_Searchs_keywords_OrderByInput',
    {
        'keywords': 'SortOrder',
    },
    total=True
)

SearchsOrderByInput = Union[
    '_Searchs_id_OrderByInput',
    '_Searchs_title_OrderByInput',
    '_Searchs_snippet_OrderByInput',
    '_Searchs_link_OrderByInput',
    '_Searchs_keywords_OrderByInput',
]



# recursive Searchs types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

SearchsRelationFilter = TypedDict(
    'SearchsRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class SearchsListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class SearchsInclude(TypedDict, total=False):
    """Searchs relational arguments"""


    

class UsersIncludeFromSearchs(TypedDict, total=False):
    """Relational arguments for Searchs"""


class UsersIncludeFromSearchsRecursive1(TypedDict, total=False):
    """Relational arguments for Searchs"""


class UsersIncludeFromSearchsRecursive2(TypedDict, total=False):
    """Relational arguments for Searchs"""


class UsersIncludeFromSearchsRecursive3(TypedDict, total=False):
    """Relational arguments for Searchs"""


class UsersIncludeFromSearchsRecursive4(TypedDict, total=False):
    """Relational arguments for Searchs"""

    

class UsersArgsFromSearchs(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'UsersIncludeFromUsersRecursive1'


class UsersArgsFromSearchsRecursive1(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'UsersIncludeFromUsersRecursive2'


class UsersArgsFromSearchsRecursive2(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'UsersIncludeFromUsersRecursive3'


class UsersArgsFromSearchsRecursive3(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'UsersIncludeFromUsersRecursive4'


class UsersArgsFromSearchsRecursive4(TypedDict, total=False):
    """Arguments for Searchs"""
    
    

class FindManyUsersArgsFromSearchs(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive1'


class FindManyUsersArgsFromSearchsRecursive1(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive2'


class FindManyUsersArgsFromSearchsRecursive2(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive3'


class FindManyUsersArgsFromSearchsRecursive3(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    include: 'UsersIncludeFromUsersRecursive4'


class FindManyUsersArgsFromSearchsRecursive4(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['UsersOrderByInput', List['UsersOrderByInput']]
    where: 'UsersWhereInput'
    cursor: 'UsersWhereUniqueInput'
    
    

class SearchsIncludeFromSearchs(TypedDict, total=False):
    """Relational arguments for Searchs"""


class SearchsIncludeFromSearchsRecursive1(TypedDict, total=False):
    """Relational arguments for Searchs"""


class SearchsIncludeFromSearchsRecursive2(TypedDict, total=False):
    """Relational arguments for Searchs"""


class SearchsIncludeFromSearchsRecursive3(TypedDict, total=False):
    """Relational arguments for Searchs"""


class SearchsIncludeFromSearchsRecursive4(TypedDict, total=False):
    """Relational arguments for Searchs"""

    

class SearchsArgsFromSearchs(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'SearchsIncludeFromSearchsRecursive1'


class SearchsArgsFromSearchsRecursive1(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'SearchsIncludeFromSearchsRecursive2'


class SearchsArgsFromSearchsRecursive2(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'SearchsIncludeFromSearchsRecursive3'


class SearchsArgsFromSearchsRecursive3(TypedDict, total=False):
    """Arguments for Searchs"""
    include: 'SearchsIncludeFromSearchsRecursive4'


class SearchsArgsFromSearchsRecursive4(TypedDict, total=False):
    """Arguments for Searchs"""
    
    

class FindManySearchsArgsFromSearchs(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive1'


class FindManySearchsArgsFromSearchsRecursive1(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive2'


class FindManySearchsArgsFromSearchsRecursive2(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive3'


class FindManySearchsArgsFromSearchsRecursive3(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    include: 'SearchsIncludeFromSearchsRecursive4'


class FindManySearchsArgsFromSearchsRecursive4(TypedDict, total=False):
    """Arguments for Searchs"""
    take: int
    skip: int
    order_by: Union['SearchsOrderByInput', List['SearchsOrderByInput']]
    where: 'SearchsWhereInput'
    cursor: 'SearchsWhereUniqueInput'
    


FindManySearchsArgs = FindManySearchsArgsFromSearchs
FindFirstSearchsArgs = FindManySearchsArgsFromSearchs


    

class SearchsWhereInput(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntFilter']
    title: Union[str, 'types.StringFilter']
    snippet: Union[str, 'types.StringFilter']
    link: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['SearchsWhereInputRecursive1', List['SearchsWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['SearchsWhereInputRecursive1']
    OR: List['SearchsWhereInputRecursive1']
    NOT: List['SearchsWhereInputRecursive1']


class SearchsWhereInputRecursive1(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntFilter']
    title: Union[str, 'types.StringFilter']
    snippet: Union[str, 'types.StringFilter']
    link: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['SearchsWhereInputRecursive2', List['SearchsWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['SearchsWhereInputRecursive2']
    OR: List['SearchsWhereInputRecursive2']
    NOT: List['SearchsWhereInputRecursive2']


class SearchsWhereInputRecursive2(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntFilter']
    title: Union[str, 'types.StringFilter']
    snippet: Union[str, 'types.StringFilter']
    link: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['SearchsWhereInputRecursive3', List['SearchsWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['SearchsWhereInputRecursive3']
    OR: List['SearchsWhereInputRecursive3']
    NOT: List['SearchsWhereInputRecursive3']


class SearchsWhereInputRecursive3(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntFilter']
    title: Union[str, 'types.StringFilter']
    snippet: Union[str, 'types.StringFilter']
    link: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'

    # should be noted that AND and NOT should be Union['SearchsWhereInputRecursive4', List['SearchsWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['SearchsWhereInputRecursive4']
    OR: List['SearchsWhereInputRecursive4']
    NOT: List['SearchsWhereInputRecursive4']


class SearchsWhereInputRecursive4(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntFilter']
    title: Union[str, 'types.StringFilter']
    snippet: Union[str, 'types.StringFilter']
    link: Union[str, 'types.StringFilter']
    keywords: 'types.StringListFilter'



# aggregate Searchs types


    

class SearchsScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    title: Union[str, 'types.StringWithAggregatesFilter']
    snippet: Union[str, 'types.StringWithAggregatesFilter']
    link: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['SearchsScalarWhereWithAggregatesInputRecursive1']
    OR: List['SearchsScalarWhereWithAggregatesInputRecursive1']
    NOT: List['SearchsScalarWhereWithAggregatesInputRecursive1']


class SearchsScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    title: Union[str, 'types.StringWithAggregatesFilter']
    snippet: Union[str, 'types.StringWithAggregatesFilter']
    link: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['SearchsScalarWhereWithAggregatesInputRecursive2']
    OR: List['SearchsScalarWhereWithAggregatesInputRecursive2']
    NOT: List['SearchsScalarWhereWithAggregatesInputRecursive2']


class SearchsScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    title: Union[str, 'types.StringWithAggregatesFilter']
    snippet: Union[str, 'types.StringWithAggregatesFilter']
    link: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['SearchsScalarWhereWithAggregatesInputRecursive3']
    OR: List['SearchsScalarWhereWithAggregatesInputRecursive3']
    NOT: List['SearchsScalarWhereWithAggregatesInputRecursive3']


class SearchsScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    title: Union[str, 'types.StringWithAggregatesFilter']
    snippet: Union[str, 'types.StringWithAggregatesFilter']
    link: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']

    AND: List['SearchsScalarWhereWithAggregatesInputRecursive4']
    OR: List['SearchsScalarWhereWithAggregatesInputRecursive4']
    NOT: List['SearchsScalarWhereWithAggregatesInputRecursive4']


class SearchsScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Searchs arguments for searching"""
    id: Union[int, 'types.IntWithAggregatesFilter']
    title: Union[str, 'types.StringWithAggregatesFilter']
    snippet: Union[str, 'types.StringWithAggregatesFilter']
    link: Union[str, 'types.StringWithAggregatesFilter']
    keywords: Union[str, 'types.StringWithAggregatesFilter']



class SearchsGroupByOutput(TypedDict, total=False):
    id: int
    title: str
    snippet: str
    link: str
    keywords: List[str]
    _sum: 'SearchsSumAggregateOutput'
    _avg: 'SearchsAvgAggregateOutput'
    _min: 'SearchsMinAggregateOutput'
    _max: 'SearchsMaxAggregateOutput'
    _count: 'SearchsCountAggregateOutput'


class SearchsAvgAggregateOutput(TypedDict, total=False):
    """Searchs output for aggregating averages"""
    id: float


class SearchsSumAggregateOutput(TypedDict, total=False):
    """Searchs output for aggregating sums"""
    id: int


class SearchsScalarAggregateOutput(TypedDict, total=False):
    """Searchs output including scalar fields"""
    id: int
    title: str
    snippet: str
    link: str
    keywords: List[str]


SearchsMinAggregateOutput = SearchsScalarAggregateOutput
SearchsMaxAggregateOutput = SearchsScalarAggregateOutput


class SearchsMaxAggregateInput(TypedDict, total=False):
    """Searchs input for aggregating by max"""
    id: bool
    title: bool
    snippet: bool
    link: bool
    keywords: bool


class SearchsMinAggregateInput(TypedDict, total=False):
    """Searchs input for aggregating by min"""
    id: bool
    title: bool
    snippet: bool
    link: bool
    keywords: bool


class SearchsNumberAggregateInput(TypedDict, total=False):
    """Searchs input for aggregating numbers"""
    id: bool


SearchsAvgAggregateInput = SearchsNumberAggregateInput
SearchsSumAggregateInput = SearchsNumberAggregateInput


SearchsCountAggregateInput = TypedDict(
    'SearchsCountAggregateInput',
    {
        'id': bool,
        'title': bool,
        'snippet': bool,
        'link': bool,
        'keywords': bool,
        '_all': bool,
    },
    total=False,
)

SearchsCountAggregateOutput = TypedDict(
    'SearchsCountAggregateOutput',
    {
        'id': int,
        'title': int,
        'snippet': int,
        'link': int,
        'keywords': int,
        '_all': int,
    },
    total=False,
)


SearchsKeys = Literal[
    'id',
    'title',
    'snippet',
    'link',
    'keywords',
]
SearchsScalarFieldKeys = Literal[
    'id',
    'title',
    'snippet',
    'link',
    'keywords',
]
SearchsScalarFieldKeysT = TypeVar('SearchsScalarFieldKeysT', bound=SearchsScalarFieldKeys)

SearchsRelationalFieldKeys = _NoneType



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields